/**
 * /h/tag/:tag — feed page listing every published post that carries
 * the requested tag. Both a human-facing archive view and a
 * canonical URL for tag-based clustering (search engines,
 * discoverability, IndieWeb readers).
 *
 * Tags are normalized to lowercase-hyphen-only when generated by the
 * LLM (or manually saved), so the URL param is trusted after a
 * minimal shape check.
 */

import { Link, useLoaderData } from "react-router";
import type {
  LoaderFunctionArgs,
  MetaFunction,
} from "react-router";
import { getUser } from "~/utils/session.server";
import { PostCard } from "~/components/PostCard/PostCard";
import type { PostParentSnippet } from "~/components/PostCard/PostCard";
import { clientPromise } from "~/lib/mongodb";
import { serializeDocs } from "~/utils/serialize.server";
import {
  getInboxPostsByUris,
  getRemoteActors,
} from "~/utils/federation-inbox-posts.server";
import { buildMeta } from "~/utils/seo";
import { useState } from "react";

const TAG_SHAPE = /^[a-z0-9][a-z0-9-]{0,31}$/;

export const loader = async ({ request, params }: LoaderFunctionArgs) => {
  const rawTag = String(params.tag ?? "").toLowerCase();
  if (!TAG_SHAPE.test(rawTag)) {
    // Reject obviously-malformed tags outright — no reason to burn a
    // DB round trip on garbage. 404 lets the /h/* catchall render its
    // rich "not found" page.
    throw new Response("Not Found", { status: 404 });
  }

  const user = await getUser(request);
  const client = await clientPromise;
  const db = client.db("user_posts");

  const isAdmin = user?.role === "administrator";
  const filter: any = {
    tags: rawTag,
    state: { $nin: ["draft", "scheduled"] },
  };
  if (!isAdmin) filter.privacy = "Public";

  const posts = await db
    .collection("myPosts")
    .find(filter)
    .sort({ created: -1 })
    .limit(100)
    .toArray();

  // Compute related tags — the other tags that co-occur with this one
  // on the same posts. Cheap surface for lateral navigation.
  const cooccurrence = new Map<string, number>();
  for (const p of posts as any[]) {
    if (!Array.isArray(p.tags)) continue;
    for (const t of p.tags) {
      if (typeof t !== "string" || t === rawTag) continue;
      cooccurrence.set(t, (cooccurrence.get(t) ?? 0) + 1);
    }
  }
  const relatedTags = Array.from(cooccurrence.entries())
    .sort((a, b) => b[1] - a[1])
    .slice(0, 8)
    .map(([tag, count]) => ({ tag, count }));

  // Fetch reply-parent snippets so PostCards can render their inline
  // quoting cards. Mirrors the pattern in /h/index.tsx.
  const parentUris = Array.from(
    new Set(
      posts
        .map((p: any) => p.inReplyTo as string | undefined)
        .filter((u): u is string => typeof u === "string" && u.length > 0)
    )
  );
  let parentsByUri: Record<string, PostParentSnippet> = {};
  if (parentUris.length) {
    const inboxParents = await getInboxPostsByUris(parentUris);
    const authorUris = Array.from(
      new Set(Object.values(inboxParents).map((p) => p.authorActorUri))
    );
    const authors = await getRemoteActors(authorUris);
    for (const [uri, ip] of Object.entries(inboxParents)) {
      const a = authors[ip.authorActorUri];
      parentsByUri[uri] = {
        authorActorUri: ip.authorActorUri,
        displayName: a?.displayName,
        handle: a?.handle,
        fqHandle: a?.fqHandle,
        avatarUrl: a?.avatarUrl,
        content: ip.content,
        publishedMs: ip.published,
        url: ip.url,
      };
    }
  }
  for (const p of posts as any[]) {
    if (
      p.inReplyTo &&
      !parentsByUri[p.inReplyTo] &&
      p.parentSnapshot &&
      typeof p.parentSnapshot === "object"
    ) {
      const s = p.parentSnapshot;
      parentsByUri[p.inReplyTo] = {
        authorActorUri: s.authorActorUri ?? p.inReplyTo,
        displayName: s.displayName,
        handle: s.handle,
        fqHandle: s.fqHandle,
        avatarUrl: s.avatarUrl,
        content: s.content ?? "",
        publishedMs: s.publishedMs,
        url: s.url,
      };
    }
  }

  return {
    tag: rawTag,
    posts: serializeDocs(posts ?? []),
    parentsByUri,
    relatedTags,
    user,
  };
};

export const meta: MetaFunction<typeof loader> = ({ data }) => {
  if (!data) return [];
  const { tag, posts } = data as { tag: string; posts: any[] };
  const displayTag = `#${tag}`;
  const count = posts?.length ?? 0;
  const noun = count === 1 ? "post" : "posts";
  const title = `${displayTag} — Patrick Glendon McCullough`;
  const description = `${count} ${noun} tagged ${displayTag} on Patrick Glendon McCullough's personal site.`;
  return buildMeta({
    title,
    description,
    path: `/h/tag/${encodeURIComponent(tag)}`,
    ogType: "website",
    appendSiteName: false,
    jsonLd: {
      "@context": "https://schema.org",
      "@type": "CollectionPage",
      name: title,
      description,
      url: `https://pg.mccullo.ug/h/tag/${encodeURIComponent(tag)}`,
      about: { "@type": "Thing", name: tag },
    },
  });
};

export default function TagFeed() {
  const { tag, posts, parentsByUri, relatedTags } = useLoaderData<typeof loader>();
  const [editState, setEditState] = useState<{
    isOn: boolean;
    id: string | null;
  }>({ isOn: false, id: null });

  return (
    // Same h-feed wrapper as the main /h index so IndieWeb parsers
    // see this as a canonical feed of h-entries.
    <div className="h-feed">
      <span style={{ display: "none" }}>
        <data className="p-name" value={`Posts tagged #${tag}`} />
        <a className="p-author h-card" href="https://pg.mccullo.ug/h/about">
          Patrick Glendon McCullough
        </a>
      </span>
      <div className="tag-feed__header">
        <div className="tag-feed__crumbs">
          <Link to="/h">← Feed</Link>
        </div>
        <h1 className="tag-feed__title">#{tag}</h1>
        <div className="tag-feed__count">
          {posts.length} {posts.length === 1 ? "post" : "posts"}
        </div>
        {relatedTags?.length ? (
          <div className="tag-feed__related">
            <span className="tag-feed__related-label">Related:</span>
            {relatedTags.map((r: { tag: string; count: number }) => (
              <Link
                key={r.tag}
                to={`/h/tag/${encodeURIComponent(r.tag)}`}
                className="postcard__tag-chip"
              >
                #{r.tag}
              </Link>
            ))}
          </div>
        ) : null}
      </div>
      {posts.length === 0 ? (
        <PostCard
          post={null}
          editState={null}
          setEditState={null}
          title="No posts"
          message={`No posts tagged #${tag} yet.`}
        />
      ) : (
        posts.map((post: any) => (
          <PostCard
            key={post._id}
            editState={editState}
            setEditState={setEditState}
            post={post}
            parent={post.inReplyTo ? parentsByUri?.[post.inReplyTo] : null}
          />
        ))
      )}
    </div>
  );
}
